name: run ostep project tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: git nasm build-essential qemu gdb
        version: 1.0
    - name: run initial-xv6
      working-directory: initial-xv6
      run: bash test-getreadcount.sh
      

